services:
  addressdb:
    image: mongo
    container_name: addressdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: swingkart
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: addressdb
    ports:
      - "27017:27017"
    networks:
      - addressdb-network


# TODO: Enable the database container for productdb.
#  productdb:
#    image: mongo
#    container_name: productdb
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: swingkart
#      MONGO_INITDB_ROOT_PASSWORD: password
#      MONGO_INITDB_DATABASE: productdb
#    ports:
#      - "27018:27017"
#    networks:
#      - productdb-network

  postgres:
    image: postgres:17.0-alpine3.19
    container_name: postgres
    environment:
      POSTGRES_USER: swingkart
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
networks:
  addressdb-network:
    driver: bridge
#  productdb-network:
#    driver: bridge

